services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-blog-app
    container_name: laravel-blog-app
    ports:
      - "3000:3000"
    volumes:
      - ./laravel-blog:/var/www/html
